import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			className='bg-white'>
			<body className='box-content flex min-h-screen max-w-full flex-col justify-start'>
				<Navbar />
				<main className='flex flex-1 flex-col max-w-7xl w-full  mx-auto'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
