import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body className="box-content flex min-h-screen max-w-full flex-col justify-start">
        <Navbar />
        <main className="mx-auto flex w-full max-w-7xl flex-1 flex-col">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
